services:
  postgres:
    container_name: pg_db
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ralaporAdmin
      POSTGRES_PASSWORD: ralaporAdmin
      POSTGRES_DB: ralapor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - '11211:11211'
    restart: unless-stopped

volumes:
  postgres_data:
